server:
  port: 8080

spring:
  cloud:
    gateway:
      routes:
        - id: warehouse_route
          uri: lb://warehouse
          predicates:
            - Path=/warehouse/**
          filters:
            - PrefixPath=/api/v1
        - id: delivery_service_route
          uri: lb://delivery
          predicates:
            - Path=/delivery/**
          filters:
            - PrefixPath=/api/v1
        - id: order_service_route
          uri: lb://order
          predicates:
            - Path=/order/**
          filters:
            - PrefixPath=/api/v1
        - id: payment_service_route
          uri: lb://payment
          predicates:
            - Path=/payment/**
          filters:
            - PrefixPath=/api/v1