server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres-cart-db
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update