kafka.topic.telemetry.sensors-topic=telemetry.sensors.v1
kafka.topic.telemetry.hubs-topic=telemetry.hubs.v1
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer
spring.kafka.properties.acks=all
spring.kafka.properties.linger.ms=5
spring.kafka.properties.batch.size=16384
spring.kafka.properties.buffer.memory=33554432

grpc.server.port=59091