server:
  port: 0

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5436/postgres-order-db
    username: username
    password: password

  jpa:
    hibernate:
      ddl-auto: update