aggregator.kafka.producer.topic=telemetry.snapshots.v1
aggregator.kafka.consumer.topic=telemetry.sensors.v1

aggregator.kafka.bootstrap-servers=localhost:9092

aggregator.kafka.producer.properties.key.serializer=org.apache.kafka.common.serialization.StringSerializer
aggregator.kafka.producer.properties.value.serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

aggregator.kafka.consumer.properties.key.deserializer=org.apache.kafka.common.serialization.StringDeserializer
aggregator.kafka.consumer.properties.value.deserializer=ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
aggregator.kafka.consumer.properties.group.id=sensorEvent.group.id
aggregator.kafka.consumer.properties.client.id=SensorEventConsumer
aggregator.kafka.consumer.properties.enable.auto.commit=false
aggregator.kafka.consumer.properties.auto.offset.reset=earliest


spring.cloud.config.enabled=false
spring.cloud.config.import-check.enabled=false