aggregator.topic.telemetry-snapshots=telemetry.snapshots.v1
topic.telemetry.sensors-topic=telemetry.sensors.v1

spring.kafka.bootstrap-servers=localhost:9092

spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer

spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer
spring.kafka.consumer.group-id=sensorEvent.group.id
spring.kafka.consumer.client-id=SensorEventConsumer
spring.kafka.consumer.enable-auto-commit=false
spring.kafka.consumer.auto-offset-reset=earliest