grpc:
  server:
    port: 59091

collector:
  kafka:
    bootstrap-servers: "localhost:9092"
    producer:
      "bootstrap.servers": ${collector.kafka.bootstrap-servers}
      "key.serializer": "org.apache.kafka.common.serialization.StringSerializer"
      "value.serializer": "ru.yandex.practicum.kafka.serializer.GeneralAvroSerializer"

    properties:
      "acks": "all"
      "linger.ms": 5
      "batch.size": 16384
      "buffer.memory": 33554432

    topics:
      "sensors-topic": "telemetry.sensors.v1"
      "hubs-topic": "telemetry.hubs.v1"